# Generated by Django 2.1.1 on 2020-04-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200413_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktag',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booktag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='userpublisher',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='userpublisher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='BookTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserPublisher',
        ),
    ]
