# Generated by Django 2.1.1 on 2020-03-30 05:20

import demo.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200330_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='author_photos', validators=[demo.utils.validators.validate_file_size, demo.utils.validators.validate_extension]),
        ),
    ]
